### ISSUE TITLE
How to default an option that is for a multi-select value.

### ISSUE THREAD

**Issue by trentdavida** [outofcoffee/corebot#17]
I can't figure out how to default an option that is for a multi-select value.
```
  prod-stage:
    jobId: 16897f73-834a-4b80-8068-8714eb22a87c
    template: stage {Version}
    tags:
      - deploy
    options:
      Host:
        value: prod
      Targets:
        value: "weba, webb, dba, dbb"
```
It works if I only run one of them, But I need to be able to pass the list.
