### ISSUE TITLE
Add 'release' as alias for 'return' item action

### ISSUE THREAD

**Issue by outofcoffee** [outofcoffee/corebot#28]
This is a specific instance of #20

**Comment by pcornish** [comment]
FYI @joshuaredmond

**Comment by pcornish** [comment]
ping @JoshuaRedmond

**Comment by outofcoffee** [comment]
Updated the following templates in `items-templates.yml`:

```yaml
returnItem:
  - template: return {itemName}
  - template: release {itemName}  # <-- new

statusAllItems:
  - template: status
  - template: list  # <-- new
```
