### ISSUE TITLE
Trying to pass '@user' as value renders '. . .'

### ISSUE THREAD

**Issue by trentdavida** [outofcoffee/corebot#9]

**Comment by outofcoffee** [comment]
Hi David. This is a nice idea for a feature. Would you be able to provide an example of your configuration?

**Comment by outofcoffee** [comment]
@trentdavida Alternatively, we could implement this as a list of users to alert when a job is triggered. For example:

```
actions:
  deploy-services:
    driver: jenkins
    jobId: "example"
    template: deploy services {version} to {environment}
    notify:
      - outofcoffee
      - trentdavida
```

...and then this could cause the message to be suffixed with:

```
FYI @outofcoffee @trentdavida
```

What do you think?
